server:
  port: 0
  undertow:
    worker-threads: 10

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: us-east-2
    eurekaServerPort: 9091
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: prod.microservices.com
    preferSameZone: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
