server:
  port: 0

info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    ORDER-COMPOSITE-SERVICE:
      path: /ordercomposite/**
#      stripPrefix: false

eureka:
  environmnent: aws
  
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: us-east-2
    eurekaServerPort: 9091
    useDnsForFetchingServiceUrls: true
    eurekaServerDNSName: prod.microservices.com
    eurekaServerURLContext: eureka
    preferSameZone: false
    availabilityZones:
      us-east-2: us-east-2a, us-east-2b
      
  instance:
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  
  datacenter: cloud
