server:
 port: 9094
 undertow:
  worker-threads: 10
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9091//eureka}
    healthcheck:
       enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}} 
